name: Fetch extension and create PR
on: workflow_dispatch
jobs:
    fetch-and-pr:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                repository: 'KevinBatdorf/laravel-forge-raycast'
                path: 'extensions/laravel-forge'
            - name: Clean up files for store
              run: |
                rm -rf ./extensions/laravel-forge/.github
                rm -rf ./extensions/laravel-forge/.git
                rm ./extensions/laravel-forge/assets/screenshot*
                sed -i '/To run the dev build, you can/,$d' ./extensions/laravel-forge/README.md
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                commit-message: Update Laravel Forge Extension
                title: Update Laravel Forge Extension
                body: Latest updates from the Laravel Forge extension
                branch: update-laravel-forge-extension
                branch-suffix: random
